[phases.setup]
nixPkgs = ["python311", "nodejs_20", "bash", "curl"]

[phases.install]
cmds = [
  "python -m ensurepip",
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "playwright install --with-deps chromium"
]

[start]
cmd = "python app.py"
